version: '3'
services:
  nginx:
    image: nginx:1.20
    container_name: SKELETON_NGINX
    ports:
      - "8099:80"
    volumes:
      - ./:/app
      - ./docker-conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: SKELETON_PHP_FPM
    build:
      context: ./docker-conf/php
    volumes:
      - ./:/app
    env_file:
      - "./.env"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "3"


networks:
  app-network:
    driver: bridge